[general]
  import = [
    "~/.config/alacritty/gruvbox_dark.toml"
  ]

[window]
  startup_mode = "Fullscreen"
  opacity = 0.7

[font]
  size =11

[selection]
  save_to_clipboard = true

[mouse]
  hide_when_typing = true

[keyboard]
  bindings = [
               { key = "F11", action = "ToggleFullscreen" }
             ]

