[general]
  import = [
    "~/.config/alacritty/gruvbox_dark.toml"
  ]

[window]
  startup_mode = "Fullscreen"
  opacity = 0.7

[font]
  size = 10

[font.bold]
  family = "SauceCodePro Nerd Font"
  style = "Bold"

[font.bold_italic]
  family = "SauceCodePro Nerd Font"
  style = "Bold Italic"

[font.italic]
  family = "SauceCodePro Nerd Font"
  style = "Italic"

[font.normal]
  family = "SauceCodePro Nerd Font"
  style = "Regular"

[selection]
  save_to_clipboard = true

[mouse]
  hide_when_typing = true

[keyboard]
  bindings = [
               { key = "F11", action = "ToggleFullscreen" }
             ]

